apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cautious-perch-python 
  janus-idp.io/tekton: cautious-perch-python
  backstage.io/kubernetes-id: cautious-perch-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cautious-perch-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  